config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<div class="container">
  <h1 class="my-4">Add a movie to <%= @list.name %></h1>
  <%= simple_form_for [@list, @bookmark], html: { class: 'mb-4' } do |f| %>
    <div class="form-group">
      <%= f.association :movie, prompt: 'Select a movie', label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= f.input :comment, label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
    </div>
    <%= f.submit 'Add movie', class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'Back', list_path(@list), class: 'btn btn-secondary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="container">
  <h1 class="my-4">My Lists</h1>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-body">
            <h5 class="card-title"><%= list.name %></h5>
            <%= link_to 'View List', list_path(list), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Create a new list', new_list_path, class: 'btn btn-success' %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1 class="my-4">New List</h1>
  <%= simple_form_for @list, html: { class: 'mb-4' } do |f| %>
    <div class="form-group">
      <%= f.input :name, label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
    </div>
    <%= f.submit 'Create List', class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'Back', lists_path, class: 'btn btn-secondary' %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1 class="my-4"><%= @list.name %></h1>

  <ul class="list-group">
    <% @list.bookmarks.each do |bookmark| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center">
          <%= image_tag bookmark.movie.poster_url, class: 'img-thumbnail me-3', size: "50x75" %>
          <div>
            <strong><%= bookmark.movie.title %></strong><br>
            <%= bookmark.comment %>
          </div>
        </div>
        <%= link_to 'Delete', bookmark_path(bookmark), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
      </li>
    <% end %>
  </ul>

  <div class="mt-4">
    <%= simple_form_for [@list, @bookmark], html: { class: 'mb-4' } do |f| %>
      <div class="form-group">
        <%= f.association :movie, collection: @movies, prompt: 'Select a movie', label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
      </div>
      <div class="form-group">
        <%= f.input :comment, label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
      </div>
      <%= f.submit 'Add movie', class: 'btn btn-primary' %>
    <% end %>
    <%= link_to 'Back', lists_path, class: 'btn btn-secondary' %>
  </div>
</div>